### ISSUE TITLE
只在某些目录中工作

### ISSUE THREAD

**Issue by RightL** [Qusic/atom-youcompleteme#10]
Global Extra Path：/home/right/.ycm_extra_conf.py
Python Exe : /usr/bin/python
只要以前成功工作过的目录下有用，其他的都不行......

**Comment by RightL** [comment]
还有，怎样让ycmd.coffee正常呢？
TypeError: Object #<Object> has no method 'spawnSync'
    at Object.ycmd.spawn (/home/right/.atom/packages/you-complete-me/ycmd.coffee:19:28)
    at Object.ycmd.fetch (/home/right/.atom/packages/you-complete-me/ycmd.coffee:31:21)
    at Object.<anonymous> (/home/right/.atom/packages/you-complete-me/ycmd.coffee:60:15)
    at Object.<anonymous> (/home/right/.atom/packages/you-complete-me/ycmd.coffee:74:4)
    at Module._compile (module.js:456:26)
    at Object.exports.run (/usr/lib/coffee-script/lib/coffee-script/coffee-script.js:83:25)
    at compileScript (/usr/lib/coffee-script/lib/coffee-script/command.js:177:29)
    at /usr/lib/coffee-script/lib/coffee-script/command.js:152:18
    at fs.js:268:14
    at Object.oncomplete (fs.js:107:15)

**Comment by Qusic** [comment]
ycmd.coffee那个应该是你的node版本太旧了，更新一下或者换iojs试试。
然后按照README写的配置一下ycmd。以前是可以用vim的ycmd但是新版本为了能补全参数的占位符就得另外装一个版本的ycmd了。
