### ISSUE TITLE
Error loading custom .ycm_extra_conf.py

### ISSUE THREAD

**Issue by rubber-duck** [Qusic/atom-youcompleteme#26]
The code to load custom .ycm_extra_conf.py is wrong, first bug is easy to solve in utility.coffee you are missing `handler = require './handler'` but after that I get the following exception (note I added one line on top so the line number is +1 to trunk)

1. add `handler = require './handler'` on top of utility.coffee
2. Add .ycm_extra_conf.py file to your project tree   
3. When saving a c++ file you get dialog asking to load or ignore the file extra_conf file  
4. Confirmation results in the error below   

**Atom Version**: 1.0.6
**System**: "Fedora release
**Thrown From**: [you-complete-me](https://github.com/Qusic/atom-youcompleteme) package, v0.6.1

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /home/rafael/.atom/packages/you-complete-me/lib/utility.coffee:46

TypeError: undefined is not a function
  at atom.confirm.buttons.Load (/home/rafael/.atom/packages/you-complete-me/lib/utility.coffee:46:26)
  at Atom.module.exports.Atom.confirm (/usr/share/atom/resources/app.asar/src/atom.js:767:49)
  at confirmExtraConfig (/home/rafael/.atom/packages/you-complete-me/lib/utility.coffee:42:10)
  at Object.handleException (/home/rafael/.atom/packages/you-complete-me/lib/utility.coffee:51:36)
  at IncomingMessage.<anonymous> (/home/rafael/.atom/packages/you-complete-me/lib/handler.coffee:148:21)
  at emitNone (events.js:72:20)
  at IncomingMessage.emit (events.js:163:7)
  at _stream_readable.js:891:16
  at process._tickCallback (node.js:357:13)

```

### Commands

```
     -0:03.4.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  },
  "you-complete-me": {}
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
atom-beautify, v0.28.11
atom-material-syntax, v0.2.3
atom-material-ui, v0.5.15
atom-typescript, v5.3.0
autocomplete-python, v0.5.3
clang-format, v1.16.0
file-icons, v1.6.3
language-capnproto, v0.3.0
language-cmake, v0.1.4
language-doxygen, v0.2.1
language-gradle, v0.0.3
linter, v1.3.4
minimap, v4.12.3
you-complete-me, v0.6.1

# Dev
No dev packages
```

**Comment by Qusic** [comment]
oh ok. there is a circular dependency. i will fix it soon
