### ISSUE TITLE
Crash in ycmd on any autocomplete (python)

### ISSUE THREAD

**Issue by forivall** [Qusic/atom-youcompleteme#3]
The developer console shows the following

    [YCM] Traceback (most recent call last):
      File "/mnt/Peng/Jordan/Code/git/ycmd/third_party/bottle/bottle.py", line 861, in _handle
        return route.call(**args)
      File "/mnt/Peng/Jordan/Code/git/ycmd/third_party/bottle/bottle.py", line 1734, in wrapper
        rv = callback(*a, **ka)
      File "/mnt/Peng/Jordan/Code/git/ycmd/ycmd/../ycmd/watchdog_plugin.py", line 100, in wrapper
        return callback( *args, **kwargs )
      File "/mnt/Peng/Jordan/Code/git/ycmd/ycmd/../ycmd/hmac_plugin.py", line 54, in wrapper
        body = callback( *args, **kwargs )
      File "/mnt/Peng/Jordan/Code/git/ycmd/ycmd/../ycmd/handlers.py", line 92, in GetCompletions
        request_data )
      File "/mnt/Peng/Jordan/Code/git/ycmd/ycmd/../ycmd/server_state.py", line 106, in ShouldUseFiletypeCompleter
        request_data ) )
      File "/mnt/Peng/Jordan/Code/git/ycmd/ycmd/../ycmd/completers/completer.py", line 116, in ShouldUseNow
        if not self.ShouldUseNowInner( request_data ):
      File "/mnt/Peng/Jordan/Code/git/ycmd/ycmd/../ycmd/completers/completer.py", line 138, in ShouldUseNowInner
        current_line = request_data[ 'line_value' ]
      File "/mnt/Peng/Jordan/Code/git/ycmd/ycmd/../ycmd/request_wrap.py", line 42, in __getitem__
        value = self._computed_key[ key ]()
      File "/mnt/Peng/Jordan/Code/git/ycmd/ycmd/../ycmd/request_wrap.py", line 66, in _CurrentLine
        return contents.splitlines()[ self._request[ 'line_num' ] - 1 ]
    AttributeError: 'NoneType' object has no attribute 'splitlines'

I'm not sure if this is an issue with ycmd itself, but I figure i should put it here first.

```
  "you-complete-me":
    pythonExecutable: "/usr/bin/python2"
    ycmdPath: "/mnt/Peng/Jordan/Code/git/ycmd"
```

**Comment by Qusic** [comment]
fixed
