### ISSUE TITLE
Issue just after installing newer version of `Atom` and `atom-youcompleteme`

### ISSUE THREAD

**Issue by kaushikcfd** [Qusic/atom-youcompleteme#65]
**Atom Version**: 1.7.4
**System**: Ubuntu 14.04.4
**Thrown From**: [you-complete-me](https://github.com/Qusic/atom-youcompleteme) package, v0.7.8

### Stack Trace
```
Uncaught SyntaxError: Unexpected token }

SyntaxError: Unexpected token }
    at Object.parse (native)
    at /home/kaushikcfd/.atom/packages/you-complete-me/lib/handler.coffee:39:22
    at tryToString (fs.js:414:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)
```
### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "tree-view",
      "language-matlab"
    ],
    "themes": [
      "one-dark-ui",
      "oceanic-next"
    ]
  },
  "you-complete-me": {
    "globalExtraConfig": "/home/kaushikcfd/.vim/.ycm_extra_conf.py",
    "pythonExecutable": "/usr/bin/python2",
    "ycmdPath": "/home/kaushikcfd/MyStuff/ClonedRepos/ycmd"
  }
}
```

### Installed Packages

```coffee
# User
docblockr, v0.7.3
ink, v0.4.4
julia-client, v0.4.7
language-julia, v0.6.0
latex-completions, v0.3.1
linter, v1.11.4
minimap, v4.24.3
oceanic-next, v0.1.2
tool-bar, v0.4.0
uber-juno, v0.1.1
you-complete-me, v0.7.8
```
# Dev
No dev packages

**Comment by kaushikcfd** [comment]
**Completely** removing `ycmd` and `Atom` along with the `.atom` config directory worked. After that I started `Atom` normally and it's working fine.
