### ISSUE TITLE
Uncaught Error: spawn EACCES

### ISSUE THREAD

**Issue by ccolon944** [Qusic/atom-youcompleteme#74]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.10.2
**Electron Version**: 0.37.8
**System**: Ubuntu 16.04.1
**Thrown From**: [you-complete-me](https://github.com/Qusic/atom-youcompleteme) package, v0.7.11

### Stack Trace

Uncaught Error: spawn EACCES

```
At /usr/share/atom/resources/app.asar/src/buffered-process.js:262

Error: spawn EACCES
    at exports._errnoException (util.js:890:11)
    at ChildProcess.spawn (internal/child_process.js:302:11)
    at Object.exports.spawn (child_process.js:379:9)
    at BufferedProcess.module.exports.BufferedProcess.spawn (/usr/share/atom/resources/app.asar/src/buffered-process.js:190:44)
    at new BufferedProcess (/usr/share/atom/resources/app.asar/src/buffered-process.js:52:14)
    at /home/christian/.atom/packages/you-complete-me/lib/handler.coffee:62:19
    at startServer (/home/christian/.atom/packages/you-complete-me/lib/handler.coffee:60:38)
```

### Commands

```
     -2:54.9.0 editor:newline (atom-text-editor.editor.is-focused)
  8x -2:42 core:backspace (atom-text-editor#you-complete-me.pythonExecutable.editor.mini.is-focused)
  2x -2:36.3.0 editor:newline (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "dark-monokai-batch"
    ]
  },
  "you-complete-me": {
    "pythonExecutable": "/home/christian/ycmd/",
    "ycmdPath": "/home/christian/ycmd/"
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-python, v1.8.6 (active)
black-ui, v0.3.2 (inactive)
clang-format, v1.25.0 (active)
dark-monokai-batch, v0.5.0 (active)
linter, v1.11.18 (active)
linter-flake8, v1.13.4 (active)
python-tools, v0.6.8 (active)
you-complete-me, v0.7.11 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (active)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (inactive)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by Qusic** [comment]
Have you installed ycmd correctly?

**Comment by ccolon944** [comment]
I am able to use ycmd from terminal.

**Comment by Qusic** [comment]
The value of `pythonExecutable` config should be the full path to your `python` executable.

**Comment by ccolon944** [comment]
OK thank you that solved the problem. Now i'm getting some errors on compiler flags
 
File 0Project 0No Issuestest.cpp1:1
LFUTF-8C++
[YCM] ValueError
Still no compile flags, no completions yet.
Traceback (most recent call last):
  File "/home/christian/ycmd/third_party/bottle/bottle.py", line 861, in _handle
    return route.call(**args)
  File "/home/christian/ycmd/third_party/bottle/bottle.py", line 1734, in wrapper
    rv = callback(*a, **ka)
  File "/home/christian/ycmd/ycmd/../ycmd/watchdog_plugin.py", line 109, in wrapper
    return callback( *args, **kwargs )
  File "/home/christian/ycmd/ycmd/../ycmd/hmac_plugin.py", line 72, in wrapper
    body = callback( *args, **kwargs )
  File "/home/christian/ycmd/ycmd/../ycmd/handlers.py", line 82, in RunCompleterCommand
    request_data ) )
  File "/home/christian/ycmd/ycmd/../ycmd/completers/completer.py", line 336, in OnUserCommand
    return command( self, request_data, arguments[ 1: ] )
  File "/home/christian/ycmd/ycmd/../ycmd/completers/cpp/clang_completer.py", line 140, in <lambda>
    func = 'GetEnclosingFunctionAtLocation' ) ),
  File "/home/christian/ycmd/ycmd/../ycmd/completers/cpp/clang_completer.py", line 270, in _GetSemanticInfo
    raise ValueError( NO_COMPILE_FLAGS_MESSAGE )
ValueError: Still no compile flags, no completions yet.
Close All
[YCM] GetParent
Still no compile flags, no completions yet.

**Comment by Qusic** [comment]
You needs to setup a `.ycm_extra_conf.py` for your project to complete clang-family languages.
https://github.com/Valloric/YouCompleteMe#c-family-semantic-completion

**Comment by ccolon944** [comment]
Thank you. Things work now.
