### ISSUE TITLE
go-to-definition error

### ISSUE THREAD

**Issue by xuweitz** [Qusic/atom-youcompleteme#76]
Can't jump to definition or declaration.
Traceback (most recent call last):
  File "/home/xw/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/bottle/bottle.py", line 861, in _handle
    return route.call(**args)
  File "/home/xw/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/bottle/bottle.py", line 1734, in wrapper
    rv = callback(*a, **ka)
  File "/home/xw/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/watchdog_plugin.py", line 109, in wrapper
    return callback( *args, **kwargs )
  File "/home/xw/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/hmac_plugin.py", line 72, in wrapper
    body = callback( *args, **kwargs )
  File "/home/xw/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/handlers.py", line 82, in RunCompleterCommand
    request_data ) )
  File "/home/xw/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/completers/completer.py", line 336, in OnUserCommand
    return command( self, request_data, arguments[ 1: ] )
  File "/home/xw/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/completers/cpp/clang_completer.py", line 125, in <lambda>
    self._GoTo( request_data ) ),
  File "/home/xw/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/completers/cpp/clang_completer.py", line 200, in _GoTo
    raise RuntimeError( 'Can\'t jump to definition or declaration.' )
RuntimeError: Can't jump to definition or declaration.

**Comment by Qusic** [comment]
Mostly an issue with ycmd or its configuration.
Go-to sometimes doesn't work indeed even in vim.
