### ISSUE TITLE
YCM error when in Python 3 file

### ISSUE THREAD

**Issue by czchen** [Qusic/atom-youcompleteme#80]
The following error message is showed when trying to use this with Python 3 file.

```
[YCM] Error
Error: YCM core library compiled for Python 3 but loaded in Python 2. Set the Python Executable config to a Python 3 interpreter path.
    at exit (/home/czchen/.atom/packages/you-complete-me/lib/handler.coffee:80:34)
    at triggerExitCallback (/opt/atom/resources/app.asar/src/buffered-process.js:299:11)
    at /opt/atom/resources/app.asar/src/buffered-process.js:320:11
    at Socket.<anonymous> (/opt/atom/resources/app.asar/src/buffered-process.js:181:9)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

I has changed the Python executable to Python 3, but the problem remains.

**Comment by Qusic** [comment]
https://github.com/Qusic/atom-youcompleteme/commit/ee3844ab8845a64069e7ce7ab880fad179dd6887
This commit hasn't been published.
The error message is inverted by mistake. You should be ok to use python 2.

**Comment by czchen** [comment]
@Qusic 

Thanks for the help.
