### ISSUE TITLE
[YCM] TypeError

### ISSUE THREAD

**Issue by Al-Nibras** [Qusic/atom-youcompleteme#85]
TypeError: Key must be a buffer
    at new Hmac (crypto.js:91:16)
    at Object.Hmac (crypto.js:89:12)
    at generateHmac (/Users/al-nibras/.atom/packages/you-complete-me/lib/handler.coffee:102:12)
    at signMessage (/Users/al-nibras/.atom/packages/you-complete-me/lib/handler.coffee:113:65)
    at /Users/al-nibras/.atom/packages/you-complete-me/lib/handler.coffee:164:7

this issue is still not fixed even after applying this commit:
https://github.com/Qusic/atom-youcompleteme/blob/master/lib/handler.coffee#L89-L98

**Comment by njlr** [comment]
I am also having this issue on macOS with Atom 1.19.0.

**Comment by MagusLucius** [comment]
problem still exists in Atom 1.21.0

**Comment by gokhansolak** [comment]
I have the same problem in Ubuntu 16.04, Atom 1.24.1.
