### ISSUE TITLE
Failed to activate the you-complete-me package

### ISSUE THREAD

**Issue by scottgeigel** [Qusic/atom-youcompleteme#93]
[Enter steps to reproduce:]

1. install ycmd from ubuntu's package repo (sudo apt install ycmd)
2. place https://raw.githubusercontent.com/Valloric/ycmd/master/ycmd/default_settings.json in ~/ycmd/ycmd/default_settings.json
3. start the atom you-complete-me plugin

**Atom**: 1.30.0 x64
**Electron**: 2.0.5
**OS**: Ubuntu 18.04.1
**Thrown From**: [you-complete-me](https://github.com/Qusic/atom-youcompleteme) package 0.8.1

### Stack Trace

Failed to activate the you-complete-me package

```
At Arguments to CompositeDisposable.add must have a .dispose() method

TypeError: Arguments to CompositeDisposable.add must have a .dispose() method
    at assertDisposable (/usr/share/atom/resources/app/node_modules/event-kit/lib/composite-disposable.js:74:19)
    at CompositeDisposable.module.exports.CompositeDisposable.add (/usr/share/atom/resources/app/node_modules/event-kit/lib/composite-disposable.js:43:17)
    at Object.consumeProvider (/usr/share/atom/resources/app/node_modules/autocomplete-plus/lib/main.js:89:27)
    at Object.consumeProvider_2 (/usr/share/atom/resources/app/node_modules/autocomplete-plus/lib/main.js:62:23)
    at Provider.module.exports.Provider.provide (/usr/share/atom/resources/app/node_modules/service-hub/lib/provider.js:34:58)
    at ServiceHub.module.exports.ServiceHub.provide (/usr/share/atom/resources/app/node_modules/service-hub/lib/service-hub.js:30:26)
    at Package.activateServices (/usr/share/atom/resources/app/src/package.js:397:75)
    at Package.activateNow (/usr/share/atom/resources/app/src/package.js:233:20)
    at measure (/usr/share/atom/resources/app/src/package.js:206:33)
    at Package.measure (/usr/share/atom/resources/app/src/package.js:88:25)
    at activationPromise.Promise (/usr/share/atom/resources/app/src/package.js:200:20)
    at new Promise (<anonymous>)
    at Package.activate (/usr/share/atom/resources/app/src/package.js:198:38)
    at PackageManager.activatePackage (/usr/share/atom/resources/app/src/package-manager.js:695:42)
    at packagesToEnable.forEach.name (/usr/share/atom/resources/app/src/package-manager.js:440:51)
    at Array.forEach (<anonymous>)
    at disabledPackagesSubscription.config.onDidChange (/usr/share/atom/resources/app/src/package-manager.js:440:30)
    at emitter.on (/usr/share/atom/resources/app/src/config.js:1067:22)
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at Config.emitChangeEvent (/usr/share/atom/resources/app/src/config.js:1226:62)
    at Config.setRawValue (/usr/share/atom/resources/app/src/config.js:1052:23)
    at Config.set (/usr/share/atom/resources/app/src/config.js:715:18)
    at Config.removeAtKeyPath (/usr/share/atom/resources/app/src/config.js:905:16)
    at Package.enable (/usr/share/atom/resources/app/src/package.js:75:30)
    at PackageManager.enablePackage (/usr/share/atom/resources/app/src/package-manager.js:246:18)
    at HTMLButtonElement.enablementButtonClickHandler (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-card.js:362:31)
```

### Commands

```
  4x -9:07.9.0 core:move-left (input.hidden-input)
     -9:06.9.0 editor:select-to-first-character-of-line (input.hidden-input)
     -9:06.6.0 core:delete (input.hidden-input)
  2x -9:05.5.0 core:confirm (input.hidden-input)
     -8:52.7.0 core:save (div.package-detail.panels-item)
     -8:52 core:close (div.package-detail.panels-item)
     -8:38.1.0 intentions:highlight (input.hidden-input)
     -8:37.5.0 settings-view:open (input.hidden-input)
  3x -4:55.5.0 core:backspace (input.hidden-input)
     -4:01.9.0 intentions:highlight (input.hidden-input)
     -4:01.8.0 core:save (input.hidden-input)
     -3:26.3.0 core:backspace (input.hidden-input)
     -1:36.8.0 core:copy (atom-notification.error.icon.icon-flame.native-key-bindings.has-detail.has-close)
```

### Non-Core Packages

```
atom-ide-ui 0.9.2 
busy-signal 1.4.3 
highlight-selected 0.13.1 
hyperclick 0.0.0 
ide-rust 0.14.0 
intentions 1.1.5 
language-cmake 1.1.0 
language-rust 0.4.12 
language-x86-64-assembly 2.2.11 
linter 2.2.0 
linter-ui-default 1.7.1 
you-complete-me 0.8.1 
```

**Comment by jath03** [comment]
I have the same problem on ubuntu 18.04 atom version 1.34.0 with a compiled ycmd

**Comment by scottgeigel** [comment]
I had some moderate success ignoring the installation instructions, installing ycmd from apt-get, and then tweaking the config for the plug-in. 
But it never really worked quite right.
