### ISSUE TITLE
[YCM] IOError, but YCMD worked in other editors

### ISSUE THREAD

**Issue by tan-wei** [Qusic/atom-youcompleteme#95]
YouCompleteMe works in gvim, vscode and Sublime Text, however, it crashed in Atom. `Windows 10` and `Python 2.7.15`, and YCMD is configured correctly.

```
[Errno 13] Permission denied
Traceback (most recent call last):
  File "C:\Users\Winterreise\.vim\bundle\YouCompleteMe\third_party\ycmd\third_party\bottle\bottle.py", line 862, in _handle
    return route.call(**args)
  File "C:\Users\Winterreise\.vim\bundle\YouCompleteMe\third_party\ycmd\third_party\bottle\bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "C:\Users\Winterreise\.vim\bundle\YouCompleteMe\third_party\ycmd\ycmd\watchdog_plugin.py", line 107, in wrapper
    return callback( *args, **kwargs )
  File "C:\Users\Winterreise\.vim\bundle\YouCompleteMe\third_party\ycmd\ycmd\hmac_plugin.py", line 70, in wrapper
    body = callback( *args, **kwargs )
  File "C:\Users\Winterreise\.vim\bundle\YouCompleteMe\third_party\ycmd\ycmd\handlers.py", line 70, in EventNotification
    event_handler )( request_data )
  File "C:\Users\Winterreise\.vim\bundle\YouCompleteMe\third_party\ycmd\ycmd\completers\cpp\clang_completer.py", line 382, in OnFileReadyToParse
    flags, filename = self._FlagsForRequest( request_data )
  File "C:\Users\Winterreise\.vim\bundle\YouCompleteMe\third_party\ycmd\ycmd\completers\cpp\clang_completer.py", line 481, in _FlagsForRequest
    return self._flags.FlagsForFile( filename, client_data = client_data )
  File "C:\Users\Winterreise\.vim\bundle\YouCompleteMe\third_party\ycmd\ycmd\completers\cpp\flags.py", line 137, in FlagsForFile
    results = self._GetFlagsFromExtraConfOrDatabase( filename, client_data )
  File "C:\Users\Winterreise\.vim\bundle\YouCompleteMe\third_party\ycmd\ycmd\completers\cpp\flags.py", line 176, in _GetFlagsFromExtraConfOrDatabase
    module = extra_conf_store.ModuleForSourceFile( filename )
  File "C:\Users\Winterreise\.vim\bundle\YouCompleteMe\third_party\ycmd\ycmd\extra_conf_store.py", line 66, in ModuleForSourceFile
    return Load( ModuleFileForSourceFile( filename ) )
  File "C:\Users\Winterreise\.vim\bundle\YouCompleteMe\third_party\ycmd\ycmd\extra_conf_store.py", line 77, in ModuleFileForSourceFile
    if Load( module_file ):
  File "C:\Users\Winterreise\.vim\bundle\YouCompleteMe\third_party\ycmd\ycmd\extra_conf_store.py", line 183, in Load
    module = LoadPythonSource( _RandomName(), module_file )
  File "C:\Users\Winterreise\.vim\bundle\YouCompleteMe\third_party\ycmd\ycmd\utils.py", line 452, in LoadPythonSource
    return imp.load_source( name, pathname )
IOError: [Errno 13] Permission denied
```

**Comment by tan-wei** [comment]
It seems that the problem fixed after I update Atom and Python.
